full_name = input("What is your full name? ")
age = input("How old are you? ")
faculty = input("What is your faculty? ")
birth_date = input("When is your birth date (e.g., YYYY-MM-DD)? ")
graduation_year = input("What is your graduation year? ")

print("Full Name:", full_name)
print("Age:", age)
print("Faculty:", faculty)
print("Birth Date:", birth_date)
print("Graduation Year:", graduation_year)
